REM   Script: Logistics Center Script
REM   Logistics Center Script GP Work

CREATE OR REPLACE TYPE DEALER AS OBJECT ( 
DEALER_ID NUMBER, 
DEALER_NAME VARCHAR (25), 
DEALER_ADDRESS VARCHAR (235), 
MEMBER PROCEDURE Print_Dealer ); 
/

CREATE OR REPLACE TYPE REQUEST_ORDER AS OBJECT ( 
ORDER_ID NUMBER, 
DEALER_ID NUMBER, 
MEMBER PROCEDURE Print_Order ); 
/

CREATE OR REPLACE TYPE WEBSITE AS OBJECT ( 
LOGISTICS_CENTER_ID NUMBER, 
SUPPLIER_APPLICATION VARCHAR(3), 
SUPPLIER_ID NUMBER, 
ORDER_ID NUMBER, 
CATALOGUE_ITEM_ID NUMBER, 
MEMBER PROCEDURE Print_Website_info ); 
/

CREATE OR REPLACE TYPE SUPPLIER AS OBJECT ( 
SUPPLIER_ID NUMBER, 
SUPPLIER_NAME VARCHAR (25), 
SUPPLIER_ADDRESS VARCHAR (235), 
MEMBER PROCEDURE Print_Supplier ); 
/

CREATE OR REPLACE TYPE MANUFACTURER AS OBJECT ( 
MANUFACTURER_ID NUMBER, 
MANUFACTURER_NAME VARCHAR (25), 
MANUFACTURER_ADDRESS VARCHAR (235), 
MEMBER PROCEDURE Print_Manufacturer ); 
/

CREATE OR REPLACE TYPE LOGISTICS_CENTER AS OBJECT ( 
LOGISTICS_CENTER_ID NUMBER, 
LOGISTICS_CENTER_NAME VARCHAR (42), 
MEMBER_ID NUMBER, 
WAREHOUSE_ID NUMBER, 
TRUCK_ID NUMBER, 
MEMBER PROCEDURE Print_Logistics_center_info ); 
/

CREATE OR REPLACE TYPE LOGISTICS_CENTER_MEMBERS AS OBJECT ( 
MEMBER_ID NUMBER, 
FIRST_NAME VARCHAR (42), 
LAST_NAME VARCHAR (42), 
POSITION VARCHAR (21), 
GENDER VARCHAR (6), 
BIRTH_DATE DATE, 
MEMBER PROCEDURE Print_Member ); 
/

CREATE OR REPLACE TYPE WAREHOUSE AS OBJECT ( 
WAREHOUSE_ID NUMBER, 
WAREHOUSE_LOCATION VARCHAR (235), 
MEMBER_ID NUMBER, 
MEMBER PROCEDURE Print_Warehouse ); 
/

CREATE OR REPLACE TYPE TRUCKS AS OBJECT ( 
TRUCK_ID NUMBER, 
MEMBER_ID NUMBER, 
SHIPMENT_ID NUMBER, 
MEMBER PROCEDURE Print_Trucks ); 
/

CREATE OR REPLACE TYPE SHIPMENT AS OBJECT ( 
SHIPMENT_ID NUMBER, 
PICKUP_ADDRESS VARCHAR (235), 
DELIVERY_ADDRESS VARCHAR (235), 
SHIPMENT_WEIGHT NUMBER, 
SHIPMENT_VOLUME NUMBER, 
ORDER_ID NUMBER, 
MEMBER PROCEDURE Print_Shipment ); 
/

CREATE TABLE DEALER_TABLE OF DEALER;

CREATE TABLE REQUEST_ORDER_TABLE OF REQUEST_ORDER;

CREATE TABLE WEBSITE_TABLE OF WEBSITE;

CREATE TABLE SUPPLIER_TABLE OF SUPPLIER;

CREATE TABLE MANUFACTURER_TABLE OF MANUFACTURER;

CREATE TABLE LOGISTICS_CENTER_TABLE OF LOGISTICS_CENTER;

CREATE TABLE LOGISTICS_CENTER_MEMBERS_TABLE OF LOGISTICS_CENTER_MEMBERS;

CREATE TABLE WAREHOUSE_TABLE OF WAREHOUSE;

CREATE TABLE TRUCKS_TABLE OF TRUCKS;

CREATE TABLE SHIPMENT_TABLE OF SHIPMENT;

CREATE TABLE LOGISTICS( 
L_DEALER REF DEALER SCOPE IS DEALER_TABLE, 
L_REQUEST_ORDER REF REQUEST_ORDER SCOPE IS REQUEST_ORDER_TABLE, 
L_WEBSITE REF WEBSITE SCOPE IS WEBSITE_TABLE, 
L_SUPPLIER REF SUPPLIER SCOPE IS SUPPLIER_TABLE, 
L_MANUFACTURER REF MANUFACTURER SCOPE IS MANUFACTURER_TABLE, 
L_LOGISTICS_CENTER REF LOGISTICS_CENTER SCOPE IS LOGISTICS_CENTER_TABLE, 
L_LOGISTICS_CENTER_MEMBERS REF LOGISTICS_CENTER_MEMBERS SCOPE IS LOGISTICS_CENTER_MEMBERS_TABLE, 
L_WAREHOUSE REF WAREHOUSE SCOPE IS WAREHOUSE_TABLE, 
L_TRUCKS REF TRUCKS SCOPE IS TRUCKS_TABLE, 
L_SHIPMENT REF SHIPMENT SCOPE IS SHIPMENT_TABLE 
);

INSERT INTO DEALER_TABLE VALUES('1','Patriot', '755 Main St E, North Bay, ON P1B 1C2, Canada');

INSERT INTO DEALER_TABLE VALUES('2','AVShop.ca', '235 Hood Rd Suite 1, Markham, ON L3R 4N3, Canada');

INSERT INTO DEALER_TABLE VALUES('3','Canada Computers', '1045 Wellington Road, London, ON N6E 1W4, Canada');

INSERT INTO DEALER_TABLE VALUES('4','Long & McQuade', '2506 Clearbrook Rd, Abbotsford, BC V2T 2Y2, Canada');

INSERT INTO DEALER_TABLE VALUES('5','Ct Canada', '46 Charterhouse Crescent, London, ON N5W 5V5, Canada');

INSERT INTO DEALER_TABLE VALUES('6','Economic', '215 Saint Augustin, Montréal, QC H4C 2N7, Canada');

INSERT INTO DEALER_TABLE VALUES('7','Marketing', '1160 Ellesmere Rd, Scarborough, ON M1P 2X4, Canada');

INSERT INTO DEALER_TABLE VALUES('8','Best Service', 'Manzingerweg 9, 81241 Munich, Germany');

INSERT INTO DEALER_TABLE VALUES('9','Elevator Future of Music', 'Schuckertstrasse 28, 48153 Muenster, Germany');

INSERT INTO DEALER_TABLE VALUES('10','Gear4Music', 'Lahnstrasse 27, 45478 Mülheim on the Ruhr, Germany');

INSERT INTO REQUEST_ORDER_TABLE VALUES('1','21');

INSERT INTO REQUEST_ORDER_TABLE VALUES('2','22');

INSERT INTO REQUEST_ORDER_TABLE VALUES('3','23');

INSERT INTO REQUEST_ORDER_TABLE VALUES('4','24');

INSERT INTO REQUEST_ORDER_TABLE VALUES('5','25');

INSERT INTO REQUEST_ORDER_TABLE VALUES('6','26');

INSERT INTO REQUEST_ORDER_TABLE VALUES('7','27');

INSERT INTO REQUEST_ORDER_TABLE VALUES('8','28');

INSERT INTO REQUEST_ORDER_TABLE VALUES('9','29');

INSERT INTO REQUEST_ORDER_TABLE VALUES('10','211');

INSERT INTO WEBSITE_TABLE VALUES('31', 'YES', '121','1', '81');

INSERT INTO WEBSITE_TABLE VALUES('32', 'NO', '122', '2', '82');

INSERT INTO WEBSITE_TABLE VALUES('33', 'YES', '123', '3', '83');

INSERT INTO WEBSITE_TABLE VALUES('34', 'NO', '124', '4', '84');

INSERT INTO WEBSITE_TABLE VALUES('35', 'YES', '125', '5', '85');

INSERT INTO WEBSITE_TABLE VALUES('36', 'NO', '126', '6', '86');

INSERT INTO WEBSITE_TABLE VALUES('37', 'YES', '127', '7', '87');

INSERT INTO WEBSITE_TABLE VALUES('38', 'NO', '128', '8', '88');

INSERT INTO WEBSITE_TABLE VALUES('39', 'YES', '129', '9', '89');

INSERT INTO WEBSITE_TABLE VALUES('311', 'NO', '211', '10', '811');

INSERT INTO SUPPLIER_TABLE VALUES('121','Ljudfront', 'Drabantvägen 19, 177 50 Järfälla, Sweden');

INSERT INTO SUPPLIER_TABLE VALUES('122', 'Albany Rockshop', 'Shop 16 North Ridge Plaza, 100 Don Mckinnon Dr, Albany, Auckland 0632, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('123', 'Blenheim Rockshop', '25 Scott St, Blenheim, 7201, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('124', 'Hamilton Rockshop', '342 Barton St, Hamilton Central, Hamilton 3204, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('125', 'Manukau Rockshop', '50 Cavendish Dr, Manukau, Auckland 2104, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('126', 'Napier Rockshop', '21 Dickens St, Napier 4110, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('127', 'Rotorua Rockshop', '1210 Eruera St, Rotorua 3010, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('128', 'Tauranga Rockshop', '101 Elizabeth St, Tauranga, 3110, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('129', 'Wellington Rockshop', '40 Cuba St, Te Aro, Wellington 6011, New Zealand');

INSERT INTO SUPPLIER_TABLE VALUES('211', 'Sylvia Park Rockshop', 'Shop 77 Sylvia Park Mall Sylvia Park, Mount Wellington, Auckland 1060, New Zealand');

INSERT INTO MANUFACTURER_TABLE VALUES('221','Bax Music Goes', 'Olympiastraat 4, 4462 GG Goes, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('222', 'Bax Music Rotterdam', 'Pascalweg 157-159, 3076 JN Rotterdam, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('223', 'KeyMusic Apeldoorn', 'Molenstraat-Centrum 377, 7311 XJ Apeldoorn, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('224', 'KeyMusic Eindhoven', 'Generaal Bothastraat 3, 5642 NJ Eindhoven, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('225', 'KeyMusic Utrecht', 'Biltstraat 30, 3572 BC Utrecht, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('226', 'Pro Media Connect', 'Boekweitstraat 3, 2153 GK Nieuw-Vennep, Netherlandsd');

INSERT INTO MANUFACTURER_TABLE VALUES('227', 'KeyMusic The Hague', 'Torenstraat 132a, 2513 BW Den Haag, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('228', 'KeyMusic Leeuwarden', 'Voorstreek 112, 8911 JV Leeuwarden, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('229', 'KeyMusic Groningen', 'Astraat 15, 9718 CP Groningen, Netherlands');

INSERT INTO MANUFACTURER_TABLE VALUES('230', 'Bax Music Amsterdam', 'James Wattstraat 71, 1097 DL Amsterdam, Netherlands');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('131','Beijing Huayunhaoyu', '911','1', '151');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('132', 'Bax Music Rotterdam', '912','2', '152');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('133', 'Beijing Exound', '913','3', '153');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('134', 'PUYUE DISHENG', '914','4', '154');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('135', 'XINPU DIANSHENG', '915','5', '155');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('136', 'Prodance', '916','6', '156');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('137', 'Magnus Hurtownia', '917','7', '157');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('138', 'MBS', '918','8', '158');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('139', 'Sklep Muzyczny MIDI', '919','9', '159');

INSERT INTO LOGISTICS_CENTER_TABLE VALUES('140', 'BMagnus. PH. Filipowicz P.', '921','11', '161');

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('123','Myla', 'Wall','Manager', 'F', TO_DATE('09-12-1989','DD-MM-YYYY'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('124', 'Dylan', 'Marks','Driver', 'M', TO_DATE('1968-05-21','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('125', 'Nasir', 'Woods','Worker', 'M', TO_DATE('1978-09-17','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('126', 'Macey', 'Barajas','Receptionist', 'F', TO_DATE('1985-02-11','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('127', 'Lorelai', 'Orozco','Driver', 'M', TO_DATE('1973-09-27','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('128', 'Zayden', 'Dixon','Worker', 'M', TO_DATE('1976-12-05','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('129', 'Rayna', 'Bernard','Intern', 'M', TO_DATE('1972-09-01','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('131', 'Yadira', 'Yates','Accountant', 'M', TO_DATE('1995-07-25','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('132', 'Saige', 'Johnston','Team Lead', 'F', TO_DATE('1984-09-21','YYYY-MM-DD'));

INSERT INTO LOGISTICS_CENTER_MEMBERS_TABLE VALUES('133', 'Alberto', 'Mcintyre','Worker', 'M', TO_DATE('1967-04-15','YYYY-MM-DD'));

INSERT INTO WAREHOUSE_TABLE VALUES('221', 'Lilienthalstr. 7, 53424 Remagen, Germany','911');

INSERT INTO WAREHOUSE_TABLE VALUES('222', 'Schuckertstrasse 28, 48153 Muenster, Germany', '912');

INSERT INTO WAREHOUSE_TABLE VALUES('223', 'Sonnenstrasse 15, 80331 Munich, Germany', '913');

INSERT INTO WAREHOUSE_TABLE VALUES('224', 'Great Budengasse 9-17, 50667 Köln, Germany', '914');

INSERT INTO WAREHOUSE_TABLE VALUES('225', 'Eichleitnerstrasse 34, 86159 Augsburg, Germany', '915');

INSERT INTO WAREHOUSE_TABLE VALUES('226', 'Lahnstrasse 27, 45478 Mülheim on the Ruhr, Germany', '916');

INSERT INTO WAREHOUSE_TABLE VALUES('227', 'Oranienstrasse 140 -142, 10969 Berlin, Germany', '917');

INSERT INTO WAREHOUSE_TABLE VALUES('228', 'Kaiserstrasse 175, 76133 Karlsruhe, Germany', '918');

INSERT INTO WAREHOUSE_TABLE VALUES('229', 'Fuggerstrasse 6, 49479 Ibbenbüren, Germany', '919');

INSERT INTO WAREHOUSE_TABLE VALUES('230', 'Alaunstraße 13A, 01099 Dresden, Germany', '921');

INSERT INTO TRUCKS_TABLE VALUES('151', '911', '1112');

INSERT INTO TRUCKS_TABLE VALUES('152', '912', '1113');

INSERT INTO TRUCKS_TABLE VALUES('153', '913', '1114');

INSERT INTO TRUCKS_TABLE VALUES('154', '914', '1115');

INSERT INTO TRUCKS_TABLE VALUES('155', '915', '1116');

INSERT INTO TRUCKS_TABLE VALUES('156', '916', '1117');

INSERT INTO TRUCKS_TABLE VALUES('157', '917', '1118');

INSERT INTO TRUCKS_TABLE VALUES('158', '918', '1119');

INSERT INTO TRUCKS_TABLE VALUES('159', '919', '11121');

INSERT INTO TRUCKS_TABLE VALUES('161', '921', '11122');

INSERT INTO SHIPMENT_TABLE VALUES('1112', 'Brühl 65, 04109 Leipzig, Germany', '108 Botany Rd, Alexandria, NSW 2015, Australia', '10', '456', '1');

INSERT INTO SHIPMENT_TABLE VALUES('1113', 'At the sand field 21, 76149 Karlsruhe, Germany', '394 Victoria Street, Richmond , VIC 3121, Australia', '25', '18', '2');

INSERT INTO SHIPMENT_TABLE VALUES('1114', 'Hans-Thomann-Road 1, 96138 Burgebrach, Germany', 'Newmarket Hall, Newmarket, The Liberties, Dublin, Ireland', '14', '21', '3');

INSERT INTO SHIPMENT_TABLE VALUES('1115', 'Kuninkaankatu 21, 70100 Kuopio, Finland', '29 Exchequer St, Dublin 2, D02 X310, Ireland', '32', '15', '4');

INSERT INTO SHIPMENT_TABLE VALUES('1116', 'Tyrnavantie 1, 90400 Oulu, Finland', 'Frankrijklei 88, 2000 Antwerpen, Belgium', '7', '19', '5');

INSERT INTO SHIPMENT_TABLE VALUES('1117', 'Alvar Aallon katu 1 60100 Seinäjoki, Finland', 'Rue du Midi 143, 1000 Bruxelles, Belgium', '40', '31', '6');

INSERT INTO SHIPMENT_TABLE VALUES('1118', 'Saapastie 2, 33920 Pirkkala, Finland', 'Kasteellaan 1/3, 9000 Gent, Belgium', '21', '3', '7');

INSERT INTO SHIPMENT_TABLE VALUES('1119', '108 Botany Rd, Alexandria, NSW 2015, Australia', 'Hanswijkstraat 10, 2800 Mechelen, Belgium', '82', '7', '8');

INSERT INTO SHIPMENT_TABLE VALUES('11121', '7 Loftus St, West Leederville WA 6007, Australia', 'Brugsesteenweg 29, 8800 Roeselare, Belgium', '42', '16', '9');

INSERT INTO SHIPMENT_TABLE VALUES('11122', '1267 Pacific Highway, Turramurra, NSW 2074, Australia', 'Ankerstraat 81, 9100 Sint-Niklaas, Belgium', '74', '27', '10');

INSERT INTO LOGISTICS 
SELECT REF(de), REF(re), REF(we), REF(su), REF(ma), REF(ce), REF(me), REF(wa), REF(tr), REF(sh) 
FROM DEALER_TABLE de, REQUEST_ORDER_TABLE re, WEBSITE_TABLE we, SUPPLIER_TABLE su, MANUFACTURER_TABLE ma, LOGISTICS_CENTER_TABLE ce, LOGISTICS_CENTER_MEMBERS_TABLE me, WAREHOUSE_TABLE wa, TRUCKS_TABLE tr, SHIPMENT_TABLE sh 
WHERE de.DEALER_NAME = 'Patriot' AND re.ORDER_ID = '1' AND we.SUPPLIER_APPLICATION = 'YES' AND su.SUPPLIER_NAME = 'Ljudfront' AND ma.MANUFACTURER_NAME = 'Bax Music Rotterdam' AND ce.LOGISTICS_CENTER_NAME = 'Beijing Huayunhaoyu' AND me.FIRST_NAME = 'Myla' AND wa.WAREHOUSE_LOCATION = 'Schuckertstrasse 28, 48153 Muenster, Germany' AND tr.TRUCK_ID = '151' AND sh.PICKUP_ADDRESS = 'Brühl 65, 04109 Leipzig, Germany';

SELECT dl.rs.DEALER_NAME, dl.sq.ORDER_ID 
FROM (SELECT DEREF(L_DEALER) rs, DEREF(L_REQUEST_ORDER) sq FROM LOGISTICS) dl;

SELECT lo.sa.SUPPLIER_APPLICATION, lo.sn.SUPPLIER_NAME 
FROM (SELECT DEREF(L_WEBSITE) sa, DEREF(L_SUPPLIER) sn FROM LOGISTICS) lo;

SELECT th.mn.MANUFACTURER_NAME, th.cn.LOGISTICS_CENTER_NAME 
FROM (SELECT DEREF(L_MANUFACTURER) mn, DEREF(L_LOGISTICS_CENTER) cn FROM LOGISTICS) th;

SELECT fo.fn.FIRST_NAME, fo.wl.WAREHOUSE_LOCATION 
FROM (SELECT DEREF(L_LOGISTICS_CENTER_MEMBERS) fn, DEREF(L_WAREHOUSE) wl FROM LOGISTICS) fo;

SELECT fi.ti.TRUCK_ID, fi.pa.PICKUP_ADDRESS 
FROM (SELECT DEREF(L_TRUCKS) ti, DEREF(L_SHIPMENT) pa FROM LOGISTICS) fi;

SELECT si.dn.DEALER_NAME, si.wl.WAREHOUSE_LOCATION 
FROM (SELECT DEREF(L_DEALER) dn, DEREF(L_WAREHOUSE) wl FROM LOGISTICS) si;

